config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "pages#index"
  resources :posts
  get "about", to: "pages#about"
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 3, maximum: 100}
    validates :body, presence: true, length: {minimum: 10, maximum: 2000}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :posts

    # validates :username, presence: true, uniqueness: {case_sensetive: false}, length: {minimum:3, maximum:30}
    # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    # validates :email, presence: true, uniqueness: true,uniqueness: { case_sensitive: false }, 
    # format: { with: VALID_EMAIL_REGEX }
    # before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :exception
    # helper_method :current_user, :logged_in?
    
    # def current_user
    #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # end
    
    # def logged_in?
    #     !!current_user
    # end
   
    # def require_user
    #    if !logged_in?
    #     flash[:danger] = "You must be logged in to perform that action"
    #     redirect_to root_path
    #    end
    # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end

    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:edit, :update, :show, :destroy]
    before_action :authenticate_user!, except: [:index, :show]

    def new
        #    @post = Post.new
         @post = current_user.posts.build
    end

    def index  
        @posts = Post.order("posts.created_at DESC").paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
        if @post.update(post_params)
            flash[:success] = "Post successfuly Updated"
            redirect_to post_path(@post)
        else
            flash[:success] = "Post was NOT updated"
            render "edit"
        end
    end

    def create
        @post = current_user.posts.build(post_params)
        @post.user = User.first
        if @post.save
            flash[:success] = "Your Post was successfully Created!"
            redirect_to post_path(@post)
        else
            render "new"
        end    
    end

    def show
    end

    def destroy
        @post.destroy
        flash[:success] = "Post was successfully deleted"
        redirect_to posts_path
    end
    
    private
    def post_params
        params.require(:post).permit(:title, :body)
    end

    def find_post
        @post = Post.find(params[:id])  
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    # def new
    # end

    # def create 
    #     user = User.find_by(email: params[:session][:email].downcase)
    #     if user  && user.authenticate(params[:session][:password])
    #      session[:user_id] = user.id
    #      flash[:success] = "You have successfully logged in"
    #      redirect_to users_path(user)
    #     else
    #      flash.now[:danger] = "There was something wrong with your login information"
    #      render 'new'
    #     end 
    # end

    # def destroy
    #     session[:user_id] = nil
    #     flash[:success] = "You have logged out"
    #     redirect_to root_path
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the Espresso blog #{@user.username}"
            redirect_to posts_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          flash[:success] = "your account was successfully Updated!"
          redirect_to posts_path
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def index
        @users = User.all
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size: 80})
            gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
            size = options[:size]
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
            image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to "Espresso Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Create Post", new_post_path %></li>
        <%
=begin%>
 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> 
<%
=end%>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to  "About", about_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to  "profile", user_path(current_user) %></li>
        <%end%>
        <% if !user_signed_in? %>
        <li><%= link_to  "Sign Up", new_user_registration_path %></li>
        <%end%>
        <%
=begin%>
 <li><%= link_to  "logout", destroy_user_session_path , method: :delete,data: { confirm: "Are you sure you want to log out?"}%></li> 
<%
=end%>
       
        <%
=begin%>
 <li><%= link_to  "login", login_path %></li> 
<%
=end%>
         
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EspressoBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navigation"%>
  <%= render 'shared/messages' %>
  <%= yield %>
  <%
=begin%>
 <%= debug(params) if Rails.env.development? %> 
<%
=end%>

  </body>
</html>

app/views/pages/about.html.erb
<h1 align="center">About Shin & Espresso Blog</h1>

app/views/pages/index.html.erb
<h1 align="center">Welcome to Espresso Blog V3!</h1>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="row">
 <div class="col-xs-12">
  <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :body %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of post" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>   
    <%= link_to  "Back to all posts", posts_path ,class: 'btn btn-default btn-large'%>

   </div>
  </div>
<% end %>
 </div>
</div>

app/views/posts/edit.html.erb
<h1 align="center">Edit your Post here</h1>
<%= render 'shared/errors', obj: @post %>

<div class="row">
 <div class="col-xs-12">
  <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :body %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :body, rows: 10, class: "form-control", placeholder: "Body of post" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>   
    <%= link_to  "Back to all posts", posts_path ,class: 'btn btn-default btn-large'%>
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "Are you sure?"},class: 'btn btn-default btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/posts/index.html.erb
<h1 align="center">Listing all posts</h1>
<%= render 'shared/post', obj: @posts %>
<div align="center">
 <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1 align="center">Create your first shot of Espresso blog here</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2 align="center">Title: <%= @post.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @post.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@post.user), user_path(@post.user) %></li>
    <li class="article-title"><%= link_to @post.user.username, user_path(current_user) %></li>
    <li><small><%= pluralize(@post.user.posts.count, "post") if @post.user.posts %></small></li>
   </div>
  </div>
 </ul> 
 <% end %>
 <h4 class="center description"><strong>Body:</strong></h4>
 <hr>
 <%= simple_format(@post.body) %>
 <div class="article-actions">
 <%= link_to "Edit", edit_post_path(@post), class: "btn btn-xs btn-default" %>
 <%= link_to "Back", posts_path, class: "btn btn-xs btn-default" %>
 <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>

 </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this post from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/shared/_post.html.erb
<% obj.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to post.title, post_path(post) %>
        </div>
        <div class="article-body">
          <%= truncate(post.body, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= post.user.username if post.user %>,
                    <%= time_ago_in_words(post.created_at) %> ago,
                    last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
        <% if post.user == current_user %>
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"}, class: "btn btn-xs btn-danger" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  [ <%= link_to 'Cancel request and Return to Posts Listing', posts_path %> ]
  </div> 
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Your Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>
<div align= "center">
<% @users.each do |user| %>
 <ul class="listing">
  <div class="row">
   <div class="well col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(user), user_path(user) %></li>
    <li class="article-title"><%= link_to user.username, user_path(user) %></li>
    <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
   </div>
  </div>
 </ul>
<% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.email%>'s page</h1>
<div class="row">
 <div class="col-md-4 col-md-offset-5 center">
  <%= gravatar_for @user, size: 150 %>
 </div>
</div>
<h4 align="center"><%= @user.email %>'s posts</h4>
<div align="center" class="action">
<%= link_to  "Logout", destroy_user_session_path , method: :delete,data: { confirm: "Are you sure you want to log out?"},class: 'btn btn-primary btn-large'%>
</div>
<br>
<%= render 'shared/post', obj: @user.posts%>